package weblogic.j2ee.descriptor.wl;

import java.beans.BeanDescriptor;
import java.beans.PropertyDescriptor;
import java.beans.SimpleBeanInfo;
import java.util.ArrayList;

public class JDBCConnectionPoolParamsBeanDConfigBeanInfo extends SimpleBeanInfo {
   BeanDescriptor bd = new BeanDescriptor(JDBCConnectionPoolParamsBeanDConfig.class);
   static PropertyDescriptor[] pds = null;

   public BeanDescriptor getBeanDescriptor() {
      return this.bd;
   }

   public PropertyDescriptor[] getPropertyDescriptors() {
      if (pds != null) {
         return pds;
      } else {
         ArrayList var2 = new ArrayList();

         try {
            PropertyDescriptor var1 = new PropertyDescriptor("InitialCapacity", Class.forName("weblogic.j2ee.descriptor.wl.JDBCConnectionPoolParamsBeanDConfig"), "getInitialCapacity", "setInitialCapacity");
            var1.setValue("dependency", false);
            var1.setValue("declaration", false);
            var1.setValue("configurable", true);
            var1.setValue("key", false);
            var1.setValue("dynamic", true);
            var2.add(var1);
            var1 = new PropertyDescriptor("MaxCapacity", Class.forName("weblogic.j2ee.descriptor.wl.JDBCConnectionPoolParamsBeanDConfig"), "getMaxCapacity", "setMaxCapacity");
            var1.setValue("dependency", false);
            var1.setValue("declaration", false);
            var1.setValue("configurable", true);
            var1.setValue("key", false);
            var1.setValue("dynamic", true);
            var2.add(var1);
            var1 = new PropertyDescriptor("MinCapacity", Class.forName("weblogic.j2ee.descriptor.wl.JDBCConnectionPoolParamsBeanDConfig"), "getMinCapacity", "setMinCapacity");
            var1.setValue("dependency", false);
            var1.setValue("declaration", false);
            var1.setValue("configurable", true);
            var1.setValue("key", false);
            var1.setValue("dynamic", true);
            var2.add(var1);
            var1 = new PropertyDescriptor("CapacityIncrement", Class.forName("weblogic.j2ee.descriptor.wl.JDBCConnectionPoolParamsBeanDConfig"), "getCapacityIncrement", "setCapacityIncrement");
            var1.setValue("dependency", false);
            var1.setValue("declaration", false);
            var1.setValue("configurable", true);
            var1.setValue("key", false);
            var1.setValue("dynamic", true);
            var2.add(var1);
            var1 = new PropertyDescriptor("ShrinkFrequencySeconds", Class.forName("weblogic.j2ee.descriptor.wl.JDBCConnectionPoolParamsBeanDConfig"), "getShrinkFrequencySeconds", "setShrinkFrequencySeconds");
            var1.setValue("dependency", false);
            var1.setValue("declaration", false);
            var1.setValue("configurable", true);
            var1.setValue("key", false);
            var1.setValue("dynamic", true);
            var2.add(var1);
            var1 = new PropertyDescriptor("HighestNumWaiters", Class.forName("weblogic.j2ee.descriptor.wl.JDBCConnectionPoolParamsBeanDConfig"), "getHighestNumWaiters", "setHighestNumWaiters");
            var1.setValue("dependency", false);
            var1.setValue("declaration", false);
            var1.setValue("configurable", true);
            var1.setValue("key", false);
            var1.setValue("dynamic", true);
            var2.add(var1);
            var1 = new PropertyDescriptor("ConnectionCreationRetryFrequencySeconds", Class.forName("weblogic.j2ee.descriptor.wl.JDBCConnectionPoolParamsBeanDConfig"), "getConnectionCreationRetryFrequencySeconds", "setConnectionCreationRetryFrequencySeconds");
            var1.setValue("dependency", false);
            var1.setValue("declaration", false);
            var1.setValue("configurable", true);
            var1.setValue("key", false);
            var1.setValue("dynamic", true);
            var2.add(var1);
            var1 = new PropertyDescriptor("ConnectionReserveTimeoutSeconds", Class.forName("weblogic.j2ee.descriptor.wl.JDBCConnectionPoolParamsBeanDConfig"), "getConnectionReserveTimeoutSeconds", "setConnectionReserveTimeoutSeconds");
            var1.setValue("dependency", false);
            var1.setValue("declaration", false);
            var1.setValue("configurable", true);
            var1.setValue("key", false);
            var1.setValue("dynamic", true);
            var2.add(var1);
            var1 = new PropertyDescriptor("TestFrequencySeconds", Class.forName("weblogic.j2ee.descriptor.wl.JDBCConnectionPoolParamsBeanDConfig"), "getTestFrequencySeconds", "setTestFrequencySeconds");
            var1.setValue("dependency", false);
            var1.setValue("declaration", false);
            var1.setValue("configurable", true);
            var1.setValue("key", false);
            var1.setValue("dynamic", true);
            var2.add(var1);
            var1 = new PropertyDescriptor("TestConnectionsOnReserve", Class.forName("weblogic.j2ee.descriptor.wl.JDBCConnectionPoolParamsBeanDConfig"), "isTestConnectionsOnReserve", "setTestConnectionsOnReserve");
            var1.setValue("dependency", false);
            var1.setValue("declaration", false);
            var1.setValue("configurable", true);
            var1.setValue("key", false);
            var1.setValue("dynamic", true);
            var2.add(var1);
            var1 = new PropertyDescriptor("ProfileHarvestFrequencySeconds", Class.forName("weblogic.j2ee.descriptor.wl.JDBCConnectionPoolParamsBeanDConfig"), "getProfileHarvestFrequencySeconds", "setProfileHarvestFrequencySeconds");
            var1.setValue("dependency", false);
            var1.setValue("declaration", false);
            var1.setValue("configurable", true);
            var1.setValue("key", false);
            var1.setValue("dynamic", true);
            var2.add(var1);
            var1 = new PropertyDescriptor("IgnoreInUseConnectionsEnabled", Class.forName("weblogic.j2ee.descriptor.wl.JDBCConnectionPoolParamsBeanDConfig"), "isIgnoreInUseConnectionsEnabled", "setIgnoreInUseConnectionsEnabled");
            var1.setValue("dependency", false);
            var1.setValue("declaration", false);
            var1.setValue("configurable", true);
            var1.setValue("key", false);
            var1.setValue("dynamic", false);
            var2.add(var1);
            var1 = new PropertyDescriptor("InactiveConnectionTimeoutSeconds", Class.forName("weblogic.j2ee.descriptor.wl.JDBCConnectionPoolParamsBeanDConfig"), "getInactiveConnectionTimeoutSeconds", "setInactiveConnectionTimeoutSeconds");
            var1.setValue("dependency", false);
            var1.setValue("declaration", false);
            var1.setValue("configurable", true);
            var1.setValue("key", false);
            var1.setValue("dynamic", true);
            var2.add(var1);
            var1 = new PropertyDescriptor("TestTableName", Class.forName("weblogic.j2ee.descriptor.wl.JDBCConnectionPoolParamsBeanDConfig"), "getTestTableName", "setTestTableName");
            var1.setValue("dependency", false);
            var1.setValue("declaration", false);
            var1.setValue("configurable", true);
            var1.setValue("key", false);
            var1.setValue("dynamic", true);
            var2.add(var1);
            var1 = new PropertyDescriptor("LoginDelaySeconds", Class.forName("weblogic.j2ee.descriptor.wl.JDBCConnectionPoolParamsBeanDConfig"), "getLoginDelaySeconds", "setLoginDelaySeconds");
            var1.setValue("dependency", false);
            var1.setValue("declaration", false);
            var1.setValue("configurable", true);
            var1.setValue("key", false);
            var1.setValue("dynamic", false);
            var2.add(var1);
            var1 = new PropertyDescriptor("InitSql", Class.forName("weblogic.j2ee.descriptor.wl.JDBCConnectionPoolParamsBeanDConfig"), "getInitSql", "setInitSql");
            var1.setValue("dependency", false);
            var1.setValue("declaration", false);
            var1.setValue("configurable", true);
            var1.setValue("key", false);
            var1.setValue("dynamic", false);
            var2.add(var1);
            var1 = new PropertyDescriptor("StatementCacheSize", Class.forName("weblogic.j2ee.descriptor.wl.JDBCConnectionPoolParamsBeanDConfig"), "getStatementCacheSize", "setStatementCacheSize");
            var1.setValue("dependency", false);
            var1.setValue("declaration", false);
            var1.setValue("configurable", true);
            var1.setValue("key", false);
            var1.setValue("dynamic", true);
            var2.add(var1);
            var1 = new PropertyDescriptor("StatementCacheType", Class.forName("weblogic.j2ee.descriptor.wl.JDBCConnectionPoolParamsBeanDConfig"), "getStatementCacheType", "setStatementCacheType");
            var1.setValue("dependency", false);
            var1.setValue("declaration", false);
            var1.setValue("configurable", true);
            var1.setValue("key", false);
            var1.setValue("dynamic", false);
            var2.add(var1);
            var1 = new PropertyDescriptor("RemoveInfectedConnections", Class.forName("weblogic.j2ee.descriptor.wl.JDBCConnectionPoolParamsBeanDConfig"), "isRemoveInfectedConnections", "setRemoveInfectedConnections");
            var1.setValue("dependency", false);
            var1.setValue("declaration", false);
            var1.setValue("configurable", true);
            var1.setValue("key", false);
            var1.setValue("dynamic", false);
            var2.add(var1);
            var1 = new PropertyDescriptor("SecondsToTrustAnIdlePoolConnection", Class.forName("weblogic.j2ee.descriptor.wl.JDBCConnectionPoolParamsBeanDConfig"), "getSecondsToTrustAnIdlePoolConnection", "setSecondsToTrustAnIdlePoolConnection");
            var1.setValue("dependency", false);
            var1.setValue("declaration", false);
            var1.setValue("configurable", true);
            var1.setValue("key", false);
            var1.setValue("dynamic", true);
            var2.add(var1);
            var1 = new PropertyDescriptor("StatementTimeout", Class.forName("weblogic.j2ee.descriptor.wl.JDBCConnectionPoolParamsBeanDConfig"), "getStatementTimeout", "setStatementTimeout");
            var1.setValue("dependency", false);
            var1.setValue("declaration", false);
            var1.setValue("configurable", true);
            var1.setValue("key", false);
            var1.setValue("dynamic", false);
            var2.add(var1);
            var1 = new PropertyDescriptor("ProfileType", Class.forName("weblogic.j2ee.descriptor.wl.JDBCConnectionPoolParamsBeanDConfig"), "getProfileType", "setProfileType");
            var1.setValue("dependency", false);
            var1.setValue("declaration", false);
            var1.setValue("configurable", true);
            var1.setValue("key", false);
            var1.setValue("dynamic", true);
            var2.add(var1);
            var1 = new PropertyDescriptor("JDBCXADebugLevel", Class.forName("weblogic.j2ee.descriptor.wl.JDBCConnectionPoolParamsBeanDConfig"), "getJDBCXADebugLevel", "setJDBCXADebugLevel");
            var1.setValue("dependency", false);
            var1.setValue("declaration", false);
            var1.setValue("configurable", true);
            var1.setValue("key", false);
            var1.setValue("dynamic", false);
            var2.add(var1);
            var1 = new PropertyDescriptor("CredentialMappingEnabled", Class.forName("weblogic.j2ee.descriptor.wl.JDBCConnectionPoolParamsBeanDConfig"), "isCredentialMappingEnabled", "setCredentialMappingEnabled");
            var1.setValue("dependency", false);
            var1.setValue("declaration", false);
            var1.setValue("configurable", true);
            var1.setValue("key", false);
            var1.setValue("dynamic", false);
            var2.add(var1);
            var1 = new PropertyDescriptor("DriverInterceptor", Class.forName("weblogic.j2ee.descriptor.wl.JDBCConnectionPoolParamsBeanDConfig"), "getDriverInterceptor", "setDriverInterceptor");
            var1.setValue("dependency", false);
            var1.setValue("declaration", false);
            var1.setValue("configurable", true);
            var1.setValue("key", false);
            var1.setValue("dynamic", false);
            var2.add(var1);
            var1 = new PropertyDescriptor("PinnedToThread", Class.forName("weblogic.j2ee.descriptor.wl.JDBCConnectionPoolParamsBeanDConfig"), "isPinnedToThread", "setPinnedToThread");
            var1.setValue("dependency", false);
            var1.setValue("declaration", false);
            var1.setValue("configurable", true);
            var1.setValue("key", false);
            var1.setValue("dynamic", false);
            var2.add(var1);
            var1 = new PropertyDescriptor("IdentityBasedConnectionPoolingEnabled", Class.forName("weblogic.j2ee.descriptor.wl.JDBCConnectionPoolParamsBeanDConfig"), "isIdentityBasedConnectionPoolingEnabled", "setIdentityBasedConnectionPoolingEnabled");
            var1.setValue("dependency", false);
            var1.setValue("declaration", false);
            var1.setValue("configurable", true);
            var1.setValue("key", false);
            var1.setValue("dynamic", false);
            var2.add(var1);
            var1 = new PropertyDescriptor("WrapTypes", Class.forName("weblogic.j2ee.descriptor.wl.JDBCConnectionPoolParamsBeanDConfig"), "isWrapTypes", "setWrapTypes");
            var1.setValue("dependency", false);
            var1.setValue("declaration", false);
            var1.setValue("configurable", false);
            var1.setValue("key", false);
            var1.setValue("dynamic", false);
            var2.add(var1);
            var1 = new PropertyDescriptor("FatalErrorCodes", Class.forName("weblogic.j2ee.descriptor.wl.JDBCConnectionPoolParamsBeanDConfig"), "getFatalErrorCodes", "setFatalErrorCodes");
            var1.setValue("dependency", false);
            var1.setValue("declaration", false);
            var1.setValue("configurable", false);
            var1.setValue("key", false);
            var1.setValue("dynamic", false);
            var2.add(var1);
            var1 = new PropertyDescriptor("ConnectionLabelingCallback", Class.forName("weblogic.j2ee.descriptor.wl.JDBCConnectionPoolParamsBeanDConfig"), "getConnectionLabelingCallback", "setConnectionLabelingCallback");
            var1.setValue("dependency", false);
            var1.setValue("declaration", false);
            var1.setValue("configurable", false);
            var1.setValue("key", false);
            var1.setValue("dynamic", false);
            var2.add(var1);
            var1 = new PropertyDescriptor("ConnectionHarvestMaxCount", Class.forName("weblogic.j2ee.descriptor.wl.JDBCConnectionPoolParamsBeanDConfig"), "getConnectionHarvestMaxCount", "setConnectionHarvestMaxCount");
            var1.setValue("dependency", false);
            var1.setValue("declaration", false);
            var1.setValue("configurable", true);
            var1.setValue("key", false);
            var1.setValue("dynamic", true);
            var2.add(var1);
            var1 = new PropertyDescriptor("ConnectionHarvestTriggerCount", Class.forName("weblogic.j2ee.descriptor.wl.JDBCConnectionPoolParamsBeanDConfig"), "getConnectionHarvestTriggerCount", "setConnectionHarvestTriggerCount");
            var1.setValue("dependency", false);
            var1.setValue("declaration", false);
            var1.setValue("configurable", true);
            var1.setValue("key", false);
            var1.setValue("dynamic", true);
            var2.add(var1);
            pds = (PropertyDescriptor[])((PropertyDescriptor[])var2.toArray(new PropertyDescriptor[0]));
            return pds;
         } catch (Throwable var4) {
            var4.printStackTrace();
            throw new AssertionError("Failed to create PropertyDescriptors for JDBCConnectionPoolParamsBeanDConfigBeanInfo");
         }
      }
   }
}
