package weblogic.j2ee.descriptor.wl;

import java.beans.BeanDescriptor;
import java.beans.PropertyDescriptor;
import java.beans.SimpleBeanInfo;
import java.util.ArrayList;

public class WeblogicApplicationBeanDConfigBeanInfo extends SimpleBeanInfo {
   BeanDescriptor bd = new BeanDescriptor(WeblogicApplicationBeanDConfig.class);
   static PropertyDescriptor[] pds = null;

   public BeanDescriptor getBeanDescriptor() {
      return this.bd;
   }

   public PropertyDescriptor[] getPropertyDescriptors() {
      if (pds != null) {
         return pds;
      } else {
         ArrayList var2 = new ArrayList();

         try {
            PropertyDescriptor var1 = new PropertyDescriptor("Ejb", Class.forName("weblogic.j2ee.descriptor.wl.WeblogicApplicationBeanDConfig"), "getEjb", (String)null);
            var1.setValue("dependency", false);
            var1.setValue("declaration", false);
            var1.setValue("configurable", false);
            var1.setValue("key", false);
            var1.setValue("dynamic", false);
            var2.add(var1);
            var1 = new PropertyDescriptor("Xml", Class.forName("weblogic.j2ee.descriptor.wl.WeblogicApplicationBeanDConfig"), "getXml", (String)null);
            var1.setValue("dependency", false);
            var1.setValue("declaration", false);
            var1.setValue("configurable", false);
            var1.setValue("key", false);
            var1.setValue("dynamic", false);
            var2.add(var1);
            var1 = new PropertyDescriptor("JDBCConnectionPools", Class.forName("weblogic.j2ee.descriptor.wl.WeblogicApplicationBeanDConfig"), "getJDBCConnectionPools", (String)null);
            var1.setValue("dependency", false);
            var1.setValue("declaration", false);
            var1.setValue("configurable", false);
            var1.setValue("key", false);
            var1.setValue("dynamic", false);
            var2.add(var1);
            var1 = new PropertyDescriptor("Security", Class.forName("weblogic.j2ee.descriptor.wl.WeblogicApplicationBeanDConfig"), "getSecurity", (String)null);
            var1.setValue("dependency", false);
            var1.setValue("declaration", false);
            var1.setValue("configurable", false);
            var1.setValue("key", false);
            var1.setValue("dynamic", false);
            var2.add(var1);
            var1 = new PropertyDescriptor("ApplicationParams", Class.forName("weblogic.j2ee.descriptor.wl.WeblogicApplicationBeanDConfig"), "getApplicationParams", (String)null);
            var1.setValue("dependency", false);
            var1.setValue("declaration", false);
            var1.setValue("configurable", true);
            var1.setValue("key", false);
            var1.setValue("dynamic", false);
            var2.add(var1);
            var1 = new PropertyDescriptor("ClassloaderStructure", Class.forName("weblogic.j2ee.descriptor.wl.WeblogicApplicationBeanDConfig"), "getClassloaderStructure", (String)null);
            var1.setValue("dependency", false);
            var1.setValue("declaration", false);
            var1.setValue("configurable", false);
            var1.setValue("key", false);
            var1.setValue("dynamic", false);
            var2.add(var1);
            var1 = new PropertyDescriptor("Listeners", Class.forName("weblogic.j2ee.descriptor.wl.WeblogicApplicationBeanDConfig"), "getListeners", (String)null);
            var1.setValue("dependency", false);
            var1.setValue("declaration", false);
            var1.setValue("configurable", false);
            var1.setValue("key", false);
            var1.setValue("dynamic", false);
            var2.add(var1);
            var1 = new PropertyDescriptor("SingletonServices", Class.forName("weblogic.j2ee.descriptor.wl.WeblogicApplicationBeanDConfig"), "getSingletonServices", (String)null);
            var1.setValue("dependency", false);
            var1.setValue("declaration", false);
            var1.setValue("configurable", false);
            var1.setValue("key", false);
            var1.setValue("dynamic", false);
            var2.add(var1);
            var1 = new PropertyDescriptor("Startups", Class.forName("weblogic.j2ee.descriptor.wl.WeblogicApplicationBeanDConfig"), "getStartups", (String)null);
            var1.setValue("dependency", false);
            var1.setValue("declaration", false);
            var1.setValue("configurable", false);
            var1.setValue("key", false);
            var1.setValue("dynamic", false);
            var2.add(var1);
            var1 = new PropertyDescriptor("Shutdowns", Class.forName("weblogic.j2ee.descriptor.wl.WeblogicApplicationBeanDConfig"), "getShutdowns", (String)null);
            var1.setValue("dependency", false);
            var1.setValue("declaration", false);
            var1.setValue("configurable", false);
            var1.setValue("key", false);
            var1.setValue("dynamic", false);
            var2.add(var1);
            var1 = new PropertyDescriptor("Modules", Class.forName("weblogic.j2ee.descriptor.wl.WeblogicApplicationBeanDConfig"), "getModules", (String)null);
            var1.setValue("dependency", false);
            var1.setValue("declaration", false);
            var1.setValue("configurable", false);
            var1.setValue("key", false);
            var1.setValue("dynamic", false);
            var2.add(var1);
            var1 = new PropertyDescriptor("LibraryRefs", Class.forName("weblogic.j2ee.descriptor.wl.WeblogicApplicationBeanDConfig"), "getLibraryRefs", (String)null);
            var1.setValue("dependency", false);
            var1.setValue("declaration", false);
            var1.setValue("configurable", false);
            var1.setValue("key", false);
            var1.setValue("dynamic", false);
            var2.add(var1);
            var1 = new PropertyDescriptor("FairShareRequests", Class.forName("weblogic.j2ee.descriptor.wl.WeblogicApplicationBeanDConfig"), "getFairShareRequests", (String)null);
            var1.setValue("dependency", false);
            var1.setValue("declaration", false);
            var1.setValue("configurable", true);
            var1.setValue("key", false);
            var1.setValue("dynamic", false);
            var2.add(var1);
            var1 = new PropertyDescriptor("ResponseTimeRequests", Class.forName("weblogic.j2ee.descriptor.wl.WeblogicApplicationBeanDConfig"), "getResponseTimeRequests", (String)null);
            var1.setValue("dependency", false);
            var1.setValue("declaration", false);
            var1.setValue("configurable", true);
            var1.setValue("key", false);
            var1.setValue("dynamic", false);
            var2.add(var1);
            var1 = new PropertyDescriptor("ContextRequests", Class.forName("weblogic.j2ee.descriptor.wl.WeblogicApplicationBeanDConfig"), "getContextRequests", (String)null);
            var1.setValue("dependency", false);
            var1.setValue("declaration", false);
            var1.setValue("configurable", true);
            var1.setValue("key", false);
            var1.setValue("dynamic", false);
            var2.add(var1);
            var1 = new PropertyDescriptor("MaxThreadsConstraints", Class.forName("weblogic.j2ee.descriptor.wl.WeblogicApplicationBeanDConfig"), "getMaxThreadsConstraints", (String)null);
            var1.setValue("dependency", false);
            var1.setValue("declaration", false);
            var1.setValue("configurable", true);
            var1.setValue("key", false);
            var1.setValue("dynamic", false);
            var2.add(var1);
            var1 = new PropertyDescriptor("MinThreadsConstraints", Class.forName("weblogic.j2ee.descriptor.wl.WeblogicApplicationBeanDConfig"), "getMinThreadsConstraints", (String)null);
            var1.setValue("dependency", false);
            var1.setValue("declaration", false);
            var1.setValue("configurable", true);
            var1.setValue("key", false);
            var1.setValue("dynamic", false);
            var2.add(var1);
            var1 = new PropertyDescriptor("Capacities", Class.forName("weblogic.j2ee.descriptor.wl.WeblogicApplicationBeanDConfig"), "getCapacities", (String)null);
            var1.setValue("dependency", false);
            var1.setValue("declaration", false);
            var1.setValue("configurable", true);
            var1.setValue("key", false);
            var1.setValue("dynamic", false);
            var2.add(var1);
            var1 = new PropertyDescriptor("WorkManagers", Class.forName("weblogic.j2ee.descriptor.wl.WeblogicApplicationBeanDConfig"), "getWorkManagers", (String)null);
            var1.setValue("dependency", false);
            var1.setValue("declaration", false);
            var1.setValue("configurable", true);
            var1.setValue("key", false);
            var1.setValue("dynamic", false);
            var2.add(var1);
            var1 = new PropertyDescriptor("ComponentFactoryClassName", Class.forName("weblogic.j2ee.descriptor.wl.WeblogicApplicationBeanDConfig"), "getComponentFactoryClassName", "setComponentFactoryClassName");
            var1.setValue("dependency", false);
            var1.setValue("declaration", false);
            var1.setValue("configurable", false);
            var1.setValue("key", false);
            var1.setValue("dynamic", false);
            var2.add(var1);
            var1 = new PropertyDescriptor("ApplicationAdminModeTrigger", Class.forName("weblogic.j2ee.descriptor.wl.WeblogicApplicationBeanDConfig"), "getApplicationAdminModeTrigger", (String)null);
            var1.setValue("dependency", false);
            var1.setValue("declaration", false);
            var1.setValue("configurable", true);
            var1.setValue("key", false);
            var1.setValue("dynamic", false);
            var2.add(var1);
            var1 = new PropertyDescriptor("SessionDescriptor", Class.forName("weblogic.j2ee.descriptor.wl.WeblogicApplicationBeanDConfig"), "getSessionDescriptor", (String)null);
            var1.setValue("dependency", false);
            var1.setValue("declaration", false);
            var1.setValue("configurable", false);
            var1.setValue("key", false);
            var1.setValue("dynamic", false);
            var2.add(var1);
            var1 = new PropertyDescriptor("LibraryContextRootOverrides", Class.forName("weblogic.j2ee.descriptor.wl.WeblogicApplicationBeanDConfig"), "getLibraryContextRootOverrides", (String)null);
            var1.setValue("dependency", false);
            var1.setValue("declaration", false);
            var1.setValue("configurable", false);
            var1.setValue("key", false);
            var1.setValue("dynamic", false);
            var2.add(var1);
            var1 = new PropertyDescriptor("PreferApplicationPackages", Class.forName("weblogic.j2ee.descriptor.wl.WeblogicApplicationBeanDConfig"), "getPreferApplicationPackages", (String)null);
            var1.setValue("dependency", false);
            var1.setValue("declaration", false);
            var1.setValue("configurable", false);
            var1.setValue("key", false);
            var1.setValue("dynamic", false);
            var2.add(var1);
            var1 = new PropertyDescriptor("PreferApplicationResources", Class.forName("weblogic.j2ee.descriptor.wl.WeblogicApplicationBeanDConfig"), "getPreferApplicationResources", (String)null);
            var1.setValue("dependency", false);
            var1.setValue("declaration", false);
            var1.setValue("configurable", false);
            var1.setValue("key", false);
            var1.setValue("dynamic", false);
            var2.add(var1);
            var1 = new PropertyDescriptor("FastSwap", Class.forName("weblogic.j2ee.descriptor.wl.WeblogicApplicationBeanDConfig"), "getFastSwap", (String)null);
            var1.setValue("dependency", false);
            var1.setValue("declaration", false);
            var1.setValue("configurable", false);
            var1.setValue("key", false);
            var1.setValue("dynamic", false);
            var2.add(var1);
            var1 = new PropertyDescriptor("CoherenceClusterRef", Class.forName("weblogic.j2ee.descriptor.wl.WeblogicApplicationBeanDConfig"), "getCoherenceClusterRef", (String)null);
            var1.setValue("dependency", false);
            var1.setValue("declaration", false);
            var1.setValue("configurable", false);
            var1.setValue("key", false);
            var1.setValue("dynamic", false);
            var2.add(var1);
            var1 = new PropertyDescriptor("Version", Class.forName("weblogic.j2ee.descriptor.wl.WeblogicApplicationBeanDConfig"), "getVersion", "setVersion");
            var1.setValue("dependency", false);
            var1.setValue("declaration", false);
            var1.setValue("configurable", false);
            var1.setValue("key", false);
            var1.setValue("dynamic", false);
            var2.add(var1);
            var1 = new PropertyDescriptor("SecondaryDescriptors", Class.forName("weblogic.j2ee.descriptor.wl.WeblogicApplicationBeanDConfig"), "getSecondaryDescriptors", (String)null);
            var1.setValue("dependency", Boolean.FALSE);
            var1.setValue("declaration", Boolean.FALSE);
            var1.setValue("configurable", Boolean.FALSE);
            var1.setValue("key", Boolean.FALSE);
            var1.setValue("dynamic", Boolean.FALSE);
            var2.add(var1);
            pds = (PropertyDescriptor[])((PropertyDescriptor[])var2.toArray(new PropertyDescriptor[0]));
            return pds;
         } catch (Throwable var4) {
            var4.printStackTrace();
            throw new AssertionError("Failed to create PropertyDescriptors for WeblogicApplicationBeanDConfigBeanInfo");
         }
      }
   }
}
