package weblogic.ejb.container.interfaces;

public interface MessageDrivenLocalObjectIntf {
   int MD_STATE_INIT = 1;
   int MD_STATE_PREINVOKE = 2;
   int MD_STATE_PREINVOKE_SUCCESS = 4;
   int MD_STATE_PREINVOKE_FAIL = 8;
   int MD_STATE_BUSINESS = 16;
   int MD_STATE_BUSINESS_SUCCESS = 32;
   int MD_STATE_BUSINESS_FAIL = 64;
   int MD_STATE_BEFOREDELIVERY = 128;
   int MD_STATE_BUSINESS_DELIVERY = 256;
   int MD_STATE_BUSINESS_SUCCESS_DELIVERY = 512;
   int MD_STATE_BUSINESS_FAIL_DELIVERY = 1024;
   int MD_STATE_AFTERDELIVERY = 2048;
   int MD_STATE_POSTINVOKE_CLEANUP = 4096;
   int MD_STATE_POSTINVOKE_CLEANUP_DONE = 8192;
   int MD_STATE_RELEASE = 16384;
   int ALLOWED_INIT = 24585;
   int ALLOWED_PREINVOKE = 24585;
   int ALLOWED_PREINVOKE_SUCCESS = 2;
   int ALLOWED_PREINVOKE_FAIL = 2;
   int ALLOWED_BUSINESS = 4;
   int ALLOWED_BUSINESS_SUCCESS = 16;
   int ALLOWED_BUSINESS_FAIL = 16;
   int ALLOWED_BEFOREDELIVERY = 4;
   int ALLOWED_BUSINESS_DELIVERY = 128;
   int ALLOWED_BUSINESS_SUCCESS_DELIVERY = 256;
   int ALLOWED_BUSINESS_FAIL_DELIVERY = 256;
   int ALLOWED_AFTERDELIVERY = 1536;
   int ALLOWED_POSTINVOKE_CLEANUP = 2144;
   int ALLOWED_POSTINVOKE_CLEANUP_DONE = 4096;
   int ALLOWED_RELEASE = 26241;
}
