package weblogic.auddi.uddi;

public interface UDDILengths {
   int KEY_LENGTH = 36;
   int STRING_LENGTH = 255;
   int ACCESS_POINT_LENGTH = 255;
   int ADDRESS_LINE_LENGTH = 80;
   int AUTH_INFO_LENGTH = 4096;
   int AUTHORIZED_NAME_LENGTH = 255;
   int BINDING_KEY_LENGTH = 36;
   int BUSINESS_KEY_LENGTH = 36;
   int DESCRIPTION_LENGTH = 255;
   int DISCOVERY_URL_LENGTH = 255;
   int EMAIL_LENGTH = 255;
   int FROM_KEY_LENGTH = 36;
   int HOSTING_REDIRECTOR_LENGTH = 36;
   int INSTANCE_PARMS_LENGTH = 255;
   int KEY_NAME_LENGTH = 255;
   int KEY_TYPE_LENGTH = 16;
   int KEY_VALUE_LENGTH = 255;
   int NAME_LENGTH = 255;
   int OPERATOR_LENGTH = 255;
   int OVERVIEW_URL_LENGTH = 255;
   int PERSON_NAME_LENGTH = 255;
   int PHONE_LENGTH = 50;
   int SERVICE_KEY_LENGTH = 36;
   int SORT_CODE_LENGTH = 10;
   int TMODEL_KEY_LENGTH = 255;
   int TO_KEY_LENGTH = 36;
   int UPLOAD_REGISTER_LENGTH = 255;
   int URL_TYPE_LENGTH = 16;
   int USE_TYPE_LENGTH = 255;
}
