package weblogic.wsee.tools.wsdlc.jaxrpc;

import java.util.Date;
import weblogic.wsee.tools.source.JsMethod;
import weblogic.wsee.tools.wsdlc.WsdlcUtils;
import weblogic.wsee.util.jspgen.ScriptException;

public class JwsInterface extends JwsBase {
   public void generate() throws ScriptException {
      this.out.print("package ");
      this.out.print(this.jws.getBinding().getPackageName());
      this.out.print(";");
      this.out.print("\n");
      this.out.print("\n");
      this.out.print("import javax.jws.WebService;");
      this.out.print("\n");
      this.out.print("import javax.jws.WebMethod;");
      this.out.print("\n");
      this.out.print("import javax.jws.WebParam;");
      this.out.print("\n");
      this.out.print("import javax.jws.WebResult;");
      this.out.print("\n");
      this.out.print("import javax.jws.Oneway;");
      this.out.print("\n");
      this.out.print("import javax.jws.soap.SOAPBinding;");
      this.out.print("\n");
      String var1 = this.jws.getServiceClassName();
      this.out.print("\n");
      this.out.print("/**");
      this.out.print("\n");
      this.out.print(" * ");
      this.out.print("\n");
      this.out.print(" * <B>DO NOT EDIT!</B><BR>");
      this.out.print("\n");
      this.out.print(" * This class was generated by <I>wsdlc</I> on <I>");
      this.out.print(new Date());
      this.out.print("</I>.");
      this.out.print("\n");
      this.out.print(" * ");
      this.out.print("\n");
      this.out.print(" */");
      this.out.print("\n");
      this.out.print("\n");
      this.out.print("@WebService(");
      this.out.print("\n");
      this.out.print("  name=\"");
      this.out.print(this.jws.getBinding().getName());
      this.out.print("\",");
      this.out.print("\n");
      this.out.print("  targetNamespace=\"");
      this.out.print(this.jws.getBinding().getNamespaceURI());
      this.out.print("\",");
      this.out.print("\n");
      this.out.print("  wsdlLocation=\"");
      this.out.print(this.jws.getWsdlLocation());
      this.out.print("\")");
      this.out.print("\n");
      this.out.print(this.jws.getSOAPBindingInfo().toString());
      this.out.print("\n");
      this.out.print("public interface ");
      this.out.print(var1);
      this.out.print(" {");
      this.out.print("\n");
      this.out.print(" ");
      JsMethod[] var2 = this.jws.getBinding().getMethods();
      int var3 = var2.length;

      for(int var4 = 0; var4 < var3; ++var4) {
         JsMethod var5 = var2[var4];
         this.out.print("\n");
         this.out.print("  /**");
         this.out.print("\n");
         this.out.print("   * <B>");
         this.out.print(var5.getMethodName());
         this.out.print("</B> is exposed as a Web Service Operation");
         this.out.print("\n");
         this.out.print("   * ");
         this.out.print("\n");
         this.out.print("   */");
         this.out.print("\n");
         this.out.print("  @WebMethod(");
         if (var5.getSoapAction() != null) {
            this.out.print("    action=\"");
            this.out.print(var5.getSoapAction());
            this.out.print("\",");
            this.out.print("\n");
            this.out.print("    operationName=\"");
            this.out.print(var5.getOperationName().getLocalPart());
            this.out.print("\")");
         } else {
            this.out.print("    operationName=\"");
            this.out.print(var5.getOperationName().getLocalPart());
            this.out.print("\")");
         }

         this.out.print("\n");
         this.out.print("  ");
         this.out.print(var5.getAnnotatedReturnTypeString());
         this.out.print("  ");
         if (var5.isOneWay()) {
            this.out.print("  @Oneway");
         }

         SOAPBindingInfo var6 = new SOAPBindingInfo(var5);
         if (!var6.equals(this.jws.getSOAPBindingInfo())) {
            this.out.print("\n");
            this.out.print("  ");
            this.out.print(var6.toString());
         }

         this.out.print("\n");
         this.out.print("  public ");
         this.out.print(var5.getReturnType().getType());
         this.out.print(" ");
         this.out.print(var5.getMethodName());
         this.out.print("(");
         this.out.print(var5.getAnnotatedArgumentString());
         this.out.print(")");
         this.out.print("\n");
         this.out.print("    ");
         this.out.print(WsdlcUtils.throwException(var5));
         this.out.print(";");
         this.out.print("\n");
         this.out.print(" ");
      }

      this.out.print("}");
   }
}
