package weblogic.management.configuration;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.Map;
import java.util.Set;
import weblogic.utils.codegen.ImplementationFactory;
import weblogic.utils.codegen.RoleInfoImplementationFactory;

public class BeanInfoFactory implements RoleInfoImplementationFactory {
   private static final Map interfaceMap = new HashMap(217);
   private static final ArrayList roleInfoList;
   private static final BeanInfoFactory SINGLETON;

   public static final ImplementationFactory getInstance() {
      return SINGLETON;
   }

   public String getImplementationClassName(String var1) {
      return (String)interfaceMap.get(var1);
   }

   public String[] getInterfaces() {
      Set var1 = interfaceMap.keySet();
      return (String[])((String[])var1.toArray(new String[var1.size()]));
   }

   public String[] getInterfacesWithRoleInfo() {
      return (String[])((String[])roleInfoList.toArray(new String[roleInfoList.size()]));
   }

   public String getRoleInfoImplementationFactoryTimestamp() {
      return "1321376141560";
   }

   static {
      interfaceMap.put("weblogic.management.configuration.AdminConsoleMBean", "weblogic.management.configuration.AdminConsoleMBeanImplBeanInfo");
      interfaceMap.put("weblogic.management.configuration.AdminMBean", "weblogic.management.configuration.AdminMBeanImplBeanInfo");
      interfaceMap.put("weblogic.management.configuration.AdminServerMBean", "weblogic.management.configuration.AdminServerMBeanImplBeanInfo");
      interfaceMap.put("weblogic.management.configuration.AppDeploymentMBean", "weblogic.management.configuration.AppDeploymentMBeanImplBeanInfo");
      interfaceMap.put("weblogic.management.configuration.ApplicationMBean", "weblogic.management.configuration.ApplicationMBeanImplBeanInfo");
      interfaceMap.put("weblogic.management.configuration.BasicDeploymentMBean", "weblogic.management.configuration.BasicDeploymentMBeanImplBeanInfo");
      interfaceMap.put("weblogic.management.configuration.BasicRealmMBean", "weblogic.management.configuration.BasicRealmMBeanImplBeanInfo");
      interfaceMap.put("weblogic.management.configuration.BridgeDestinationCommonMBean", "weblogic.management.configuration.BridgeDestinationCommonMBeanImplBeanInfo");
      interfaceMap.put("weblogic.management.configuration.BridgeDestinationMBean", "weblogic.management.configuration.BridgeDestinationMBeanImplBeanInfo");
      interfaceMap.put("weblogic.management.configuration.COMMBean", "weblogic.management.configuration.COMMBeanImplBeanInfo");
      interfaceMap.put("weblogic.management.configuration.CacheAsyncListenersMBean", "weblogic.management.configuration.CacheAsyncListenersMBeanImplBeanInfo");
      interfaceMap.put("weblogic.management.configuration.CacheExpirationMBean", "weblogic.management.configuration.CacheExpirationMBeanImplBeanInfo");
      interfaceMap.put("weblogic.management.configuration.CacheLoaderMBean", "weblogic.management.configuration.CacheLoaderMBeanImplBeanInfo");
      interfaceMap.put("weblogic.management.configuration.CacheMBean", "weblogic.management.configuration.CacheMBeanImplBeanInfo");
      interfaceMap.put("weblogic.management.configuration.CacheStoreMBean", "weblogic.management.configuration.CacheStoreMBeanImplBeanInfo");
      interfaceMap.put("weblogic.management.configuration.CacheTransactionMBean", "weblogic.management.configuration.CacheTransactionMBeanImplBeanInfo");
      interfaceMap.put("weblogic.management.configuration.CachingRealmMBean", "weblogic.management.configuration.CachingRealmMBeanImplBeanInfo");
      interfaceMap.put("weblogic.management.configuration.CapacityMBean", "weblogic.management.configuration.CapacityMBeanImplBeanInfo");
      interfaceMap.put("weblogic.management.configuration.CertRevocCaMBean", "weblogic.management.configuration.CertRevocCaMBeanImplBeanInfo");
      interfaceMap.put("weblogic.management.configuration.CertRevocMBean", "weblogic.management.configuration.CertRevocMBeanImplBeanInfo");
      interfaceMap.put("weblogic.management.configuration.ClassDeploymentMBean", "weblogic.management.configuration.ClassDeploymentMBeanImplBeanInfo");
      interfaceMap.put("weblogic.management.configuration.ClusterMBean", "weblogic.management.configuration.ClusterMBeanImplBeanInfo");
      interfaceMap.put("weblogic.management.configuration.CoherenceClusterSystemResourceMBean", "weblogic.management.configuration.CoherenceClusterSystemResourceMBeanImplBeanInfo");
      interfaceMap.put("weblogic.management.configuration.CoherenceServerMBean", "weblogic.management.configuration.CoherenceServerMBeanImplBeanInfo");
      interfaceMap.put("weblogic.management.configuration.CoherenceServerStartMBean", "weblogic.management.configuration.CoherenceServerStartMBeanImplBeanInfo");
      interfaceMap.put("weblogic.management.configuration.CommonLogMBean", "weblogic.management.configuration.CommonLogMBeanImplBeanInfo");
      interfaceMap.put("weblogic.management.configuration.ComponentMBean", "weblogic.management.configuration.ComponentMBeanImplBeanInfo");
      interfaceMap.put("weblogic.management.configuration.ConfigurationExtensionMBean", "weblogic.management.configuration.ConfigurationExtensionMBeanImplBeanInfo");
      interfaceMap.put("weblogic.management.configuration.ConfigurationMBean", "weblogic.management.configuration.ConfigurationMBeanImplBeanInfo");
      interfaceMap.put("weblogic.management.configuration.ConfigurationPropertyMBean", "weblogic.management.configuration.ConfigurationPropertyMBeanImplBeanInfo");
      interfaceMap.put("weblogic.management.configuration.ConnectorComponentMBean", "weblogic.management.configuration.ConnectorComponentMBeanImplBeanInfo");
      interfaceMap.put("weblogic.management.configuration.ContextCaseMBean", "weblogic.management.configuration.ContextCaseMBeanImplBeanInfo");
      interfaceMap.put("weblogic.management.configuration.ContextRequestClassMBean", "weblogic.management.configuration.ContextRequestClassMBeanImplBeanInfo");
      interfaceMap.put("weblogic.management.configuration.ConversationServiceMBean", "weblogic.management.configuration.ConversationServiceMBeanImplBeanInfo");
      interfaceMap.put("weblogic.management.configuration.CustomRealmMBean", "weblogic.management.configuration.CustomRealmMBeanImplBeanInfo");
      interfaceMap.put("weblogic.management.configuration.CustomResourceMBean", "weblogic.management.configuration.CustomResourceMBeanImplBeanInfo");
      interfaceMap.put("weblogic.management.configuration.DataSourceLogFileMBean", "weblogic.management.configuration.DataSourceLogFileMBeanImplBeanInfo");
      interfaceMap.put("weblogic.management.configuration.DataSourceMBean", "weblogic.management.configuration.DataSourceMBeanImplBeanInfo");
      interfaceMap.put("weblogic.management.configuration.DatabaseLessLeasingBasisMBean", "weblogic.management.configuration.DatabaseLessLeasingBasisMBeanImplBeanInfo");
      interfaceMap.put("weblogic.management.configuration.DebugMBean", "weblogic.management.configuration.DebugMBeanImplBeanInfo");
      interfaceMap.put("weblogic.management.configuration.DebugScopeMBean", "weblogic.management.configuration.DebugScopeMBeanImplBeanInfo");
      interfaceMap.put("weblogic.management.configuration.DefaultFileStoreMBean", "weblogic.management.configuration.DefaultFileStoreMBeanImplBeanInfo");
      interfaceMap.put("weblogic.management.configuration.DeploymentConfigurationMBean", "weblogic.management.configuration.DeploymentConfigurationMBeanImplBeanInfo");
      interfaceMap.put("weblogic.management.configuration.DeploymentMBean", "weblogic.management.configuration.DeploymentMBeanImplBeanInfo");
      interfaceMap.put("weblogic.management.configuration.DomainLibraryMBean", "weblogic.management.configuration.DomainLibraryMBeanImplBeanInfo");
      interfaceMap.put("weblogic.management.configuration.DomainLogFilterMBean", "weblogic.management.configuration.DomainLogFilterMBeanImplBeanInfo");
      interfaceMap.put("weblogic.management.configuration.DomainMBean", "weblogic.management.configuration.DomainMBeanImplBeanInfo");
      interfaceMap.put("weblogic.management.configuration.DomainTargetedMBean", "weblogic.management.configuration.DomainTargetedMBeanImplBeanInfo");
      interfaceMap.put("weblogic.management.configuration.EJBComponentMBean", "weblogic.management.configuration.EJBComponentMBeanImplBeanInfo");
      interfaceMap.put("weblogic.management.configuration.EJBContainerMBean", "weblogic.management.configuration.EJBContainerMBeanImplBeanInfo");
      interfaceMap.put("weblogic.management.configuration.EmbeddedLDAPMBean", "weblogic.management.configuration.EmbeddedLDAPMBeanImplBeanInfo");
      interfaceMap.put("weblogic.management.configuration.ErrorHandlingMBean", "weblogic.management.configuration.ErrorHandlingMBeanImplBeanInfo");
      interfaceMap.put("weblogic.management.configuration.ExecuteQueueMBean", "weblogic.management.configuration.ExecuteQueueMBeanImplBeanInfo");
      interfaceMap.put("weblogic.management.configuration.FairShareRequestClassMBean", "weblogic.management.configuration.FairShareRequestClassMBeanImplBeanInfo");
      interfaceMap.put("weblogic.management.configuration.FederationServicesMBean", "weblogic.management.configuration.FederationServicesMBeanImplBeanInfo");
      interfaceMap.put("weblogic.management.configuration.FileRealmMBean", "weblogic.management.configuration.FileRealmMBeanImplBeanInfo");
      interfaceMap.put("weblogic.management.configuration.FileStoreMBean", "weblogic.management.configuration.FileStoreMBeanImplBeanInfo");
      interfaceMap.put("weblogic.management.configuration.FileT3MBean", "weblogic.management.configuration.FileT3MBeanImplBeanInfo");
      interfaceMap.put("weblogic.management.configuration.ForeignJMSConnectionFactoryMBean", "weblogic.management.configuration.ForeignJMSConnectionFactoryMBeanImplBeanInfo");
      interfaceMap.put("weblogic.management.configuration.ForeignJMSDestinationMBean", "weblogic.management.configuration.ForeignJMSDestinationMBeanImplBeanInfo");
      interfaceMap.put("weblogic.management.configuration.ForeignJMSServerMBean", "weblogic.management.configuration.ForeignJMSServerMBeanImplBeanInfo");
      interfaceMap.put("weblogic.management.configuration.ForeignJNDILinkMBean", "weblogic.management.configuration.ForeignJNDILinkMBeanImplBeanInfo");
      interfaceMap.put("weblogic.management.configuration.ForeignJNDIObjectMBean", "weblogic.management.configuration.ForeignJNDIObjectMBeanImplBeanInfo");
      interfaceMap.put("weblogic.management.configuration.ForeignJNDIProviderMBean", "weblogic.management.configuration.ForeignJNDIProviderMBeanImplBeanInfo");
      interfaceMap.put("weblogic.management.configuration.GenericFileStoreMBean", "weblogic.management.configuration.GenericFileStoreMBeanImplBeanInfo");
      interfaceMap.put("weblogic.management.configuration.GenericJDBCStoreMBean", "weblogic.management.configuration.GenericJDBCStoreMBeanImplBeanInfo");
      interfaceMap.put("weblogic.management.configuration.HTTPProxyMBean", "weblogic.management.configuration.HTTPProxyMBeanImplBeanInfo");
      interfaceMap.put("weblogic.management.configuration.IIOPMBean", "weblogic.management.configuration.IIOPMBeanImplBeanInfo");
      interfaceMap.put("weblogic.management.configuration.JDBCConnectionPoolMBean", "weblogic.management.configuration.JDBCConnectionPoolMBeanImplBeanInfo");
      interfaceMap.put("weblogic.management.configuration.JDBCDataSourceFactoryMBean", "weblogic.management.configuration.JDBCDataSourceFactoryMBeanImplBeanInfo");
      interfaceMap.put("weblogic.management.configuration.JDBCDataSourceMBean", "weblogic.management.configuration.JDBCDataSourceMBeanImplBeanInfo");
      interfaceMap.put("weblogic.management.configuration.JDBCMultiPoolMBean", "weblogic.management.configuration.JDBCMultiPoolMBeanImplBeanInfo");
      interfaceMap.put("weblogic.management.configuration.JDBCPoolComponentMBean", "weblogic.management.configuration.JDBCPoolComponentMBeanImplBeanInfo");
      interfaceMap.put("weblogic.management.configuration.JDBCStoreMBean", "weblogic.management.configuration.JDBCStoreMBeanImplBeanInfo");
      interfaceMap.put("weblogic.management.configuration.JDBCSystemResourceMBean", "weblogic.management.configuration.JDBCSystemResourceMBeanImplBeanInfo");
      interfaceMap.put("weblogic.management.configuration.JDBCTxDataSourceMBean", "weblogic.management.configuration.JDBCTxDataSourceMBeanImplBeanInfo");
      interfaceMap.put("weblogic.management.configuration.JMSBridgeDestinationMBean", "weblogic.management.configuration.JMSBridgeDestinationMBeanImplBeanInfo");
      interfaceMap.put("weblogic.management.configuration.JMSConnectionConsumerMBean", "weblogic.management.configuration.JMSConnectionConsumerMBeanImplBeanInfo");
      interfaceMap.put("weblogic.management.configuration.JMSConnectionFactoryMBean", "weblogic.management.configuration.JMSConnectionFactoryMBeanImplBeanInfo");
      interfaceMap.put("weblogic.management.configuration.JMSDestCommonMBean", "weblogic.management.configuration.JMSDestCommonMBeanImplBeanInfo");
      interfaceMap.put("weblogic.management.configuration.JMSDestinationKeyMBean", "weblogic.management.configuration.JMSDestinationKeyMBeanImplBeanInfo");
      interfaceMap.put("weblogic.management.configuration.JMSDestinationMBean", "weblogic.management.configuration.JMSDestinationMBeanImplBeanInfo");
      interfaceMap.put("weblogic.management.configuration.JMSDistributedDestinationMBean", "weblogic.management.configuration.JMSDistributedDestinationMBeanImplBeanInfo");
      interfaceMap.put("weblogic.management.configuration.JMSDistributedDestinationMemberMBean", "weblogic.management.configuration.JMSDistributedDestinationMemberMBeanImplBeanInfo");
      interfaceMap.put("weblogic.management.configuration.JMSDistributedQueueMBean", "weblogic.management.configuration.JMSDistributedQueueMBeanImplBeanInfo");
      interfaceMap.put("weblogic.management.configuration.JMSDistributedQueueMemberMBean", "weblogic.management.configuration.JMSDistributedQueueMemberMBeanImplBeanInfo");
      interfaceMap.put("weblogic.management.configuration.JMSDistributedTopicMBean", "weblogic.management.configuration.JMSDistributedTopicMBeanImplBeanInfo");
      interfaceMap.put("weblogic.management.configuration.JMSDistributedTopicMemberMBean", "weblogic.management.configuration.JMSDistributedTopicMemberMBeanImplBeanInfo");
      interfaceMap.put("weblogic.management.configuration.JMSFileStoreMBean", "weblogic.management.configuration.JMSFileStoreMBeanImplBeanInfo");
      interfaceMap.put("weblogic.management.configuration.JMSInteropModuleMBean", "weblogic.management.configuration.JMSInteropModuleMBeanImplBeanInfo");
      interfaceMap.put("weblogic.management.configuration.JMSJDBCStoreMBean", "weblogic.management.configuration.JMSJDBCStoreMBeanImplBeanInfo");
      interfaceMap.put("weblogic.management.configuration.JMSMessageLogFileMBean", "weblogic.management.configuration.JMSMessageLogFileMBeanImplBeanInfo");
      interfaceMap.put("weblogic.management.configuration.JMSQueueMBean", "weblogic.management.configuration.JMSQueueMBeanImplBeanInfo");
      interfaceMap.put("weblogic.management.configuration.JMSSAFMessageLogFileMBean", "weblogic.management.configuration.JMSSAFMessageLogFileMBeanImplBeanInfo");
      interfaceMap.put("weblogic.management.configuration.JMSServerMBean", "weblogic.management.configuration.JMSServerMBeanImplBeanInfo");
      interfaceMap.put("weblogic.management.configuration.JMSSessionPoolMBean", "weblogic.management.configuration.JMSSessionPoolMBeanImplBeanInfo");
      interfaceMap.put("weblogic.management.configuration.JMSStoreMBean", "weblogic.management.configuration.JMSStoreMBeanImplBeanInfo");
      interfaceMap.put("weblogic.management.configuration.JMSSystemResourceMBean", "weblogic.management.configuration.JMSSystemResourceMBeanImplBeanInfo");
      interfaceMap.put("weblogic.management.configuration.JMSTemplateMBean", "weblogic.management.configuration.JMSTemplateMBeanImplBeanInfo");
      interfaceMap.put("weblogic.management.configuration.JMSTopicMBean", "weblogic.management.configuration.JMSTopicMBeanImplBeanInfo");
      interfaceMap.put("weblogic.management.configuration.JMSVirtualDestinationMBean", "weblogic.management.configuration.JMSVirtualDestinationMBeanImplBeanInfo");
      interfaceMap.put("weblogic.management.configuration.JMXMBean", "weblogic.management.configuration.JMXMBeanImplBeanInfo");
      interfaceMap.put("weblogic.management.configuration.JPAMBean", "weblogic.management.configuration.JPAMBeanImplBeanInfo");
      interfaceMap.put("weblogic.management.configuration.JTAMBean", "weblogic.management.configuration.JTAMBeanImplBeanInfo");
      interfaceMap.put("weblogic.management.configuration.JTAMigratableTargetMBean", "weblogic.management.configuration.JTAMigratableTargetMBeanImplBeanInfo");
      interfaceMap.put("weblogic.management.configuration.JoltConnectionPoolMBean", "weblogic.management.configuration.JoltConnectionPoolMBeanImplBeanInfo");
      interfaceMap.put("weblogic.management.configuration.KernelDebugMBean", "weblogic.management.configuration.KernelDebugMBeanImplBeanInfo");
      interfaceMap.put("weblogic.management.configuration.KernelMBean", "weblogic.management.configuration.KernelMBeanImplBeanInfo");
      interfaceMap.put("weblogic.management.configuration.LDAPRealmMBean", "weblogic.management.configuration.LDAPRealmMBeanImplBeanInfo");
      interfaceMap.put("weblogic.management.configuration.LibraryMBean", "weblogic.management.configuration.LibraryMBeanImplBeanInfo");
      interfaceMap.put("weblogic.management.configuration.LogFileMBean", "weblogic.management.configuration.LogFileMBeanImplBeanInfo");
      interfaceMap.put("weblogic.management.configuration.LogFilterMBean", "weblogic.management.configuration.LogFilterMBeanImplBeanInfo");
      interfaceMap.put("weblogic.management.configuration.LogMBean", "weblogic.management.configuration.LogMBeanImplBeanInfo");
      interfaceMap.put("weblogic.management.configuration.MachineMBean", "weblogic.management.configuration.MachineMBeanImplBeanInfo");
      interfaceMap.put("weblogic.management.configuration.MailSessionMBean", "weblogic.management.configuration.MailSessionMBeanImplBeanInfo");
      interfaceMap.put("weblogic.management.configuration.ManagedExternalServerMBean", "weblogic.management.configuration.ManagedExternalServerMBeanImplBeanInfo");
      interfaceMap.put("weblogic.management.configuration.ManagedExternalServerStartMBean", "weblogic.management.configuration.ManagedExternalServerStartMBeanImplBeanInfo");
      interfaceMap.put("weblogic.management.configuration.MaxThreadsConstraintMBean", "weblogic.management.configuration.MaxThreadsConstraintMBeanImplBeanInfo");
      interfaceMap.put("weblogic.management.configuration.MessagingBridgeMBean", "weblogic.management.configuration.MessagingBridgeMBeanImplBeanInfo");
      interfaceMap.put("weblogic.management.configuration.MigratableRMIServiceMBean", "weblogic.management.configuration.MigratableRMIServiceMBeanImplBeanInfo");
      interfaceMap.put("weblogic.management.configuration.MigratableTargetMBean", "weblogic.management.configuration.MigratableTargetMBeanImplBeanInfo");
      interfaceMap.put("weblogic.management.configuration.MinThreadsConstraintMBean", "weblogic.management.configuration.MinThreadsConstraintMBeanImplBeanInfo");
      interfaceMap.put("weblogic.management.configuration.NTRealmMBean", "weblogic.management.configuration.NTRealmMBeanImplBeanInfo");
      interfaceMap.put("weblogic.management.configuration.NetworkAccessPointMBean", "weblogic.management.configuration.NetworkAccessPointMBeanImplBeanInfo");
      interfaceMap.put("weblogic.management.configuration.NetworkChannelMBean", "weblogic.management.configuration.NetworkChannelMBeanImplBeanInfo");
      interfaceMap.put("weblogic.management.configuration.NodeManagerMBean", "weblogic.management.configuration.NodeManagerMBeanImplBeanInfo");
      interfaceMap.put("weblogic.management.configuration.OverloadProtectionMBean", "weblogic.management.configuration.OverloadProtectionMBeanImplBeanInfo");
      interfaceMap.put("weblogic.management.configuration.PasswordPolicyMBean", "weblogic.management.configuration.PasswordPolicyMBeanImplBeanInfo");
      interfaceMap.put("weblogic.management.configuration.PathServiceMBean", "weblogic.management.configuration.PathServiceMBeanImplBeanInfo");
      interfaceMap.put("weblogic.management.configuration.PersistentStoreMBean", "weblogic.management.configuration.PersistentStoreMBeanImplBeanInfo");
      interfaceMap.put("weblogic.management.configuration.RDBMSRealmMBean", "weblogic.management.configuration.RDBMSRealmMBeanImplBeanInfo");
      interfaceMap.put("weblogic.management.configuration.RMCFactoryMBean", "weblogic.management.configuration.RMCFactoryMBeanImplBeanInfo");
      interfaceMap.put("weblogic.management.configuration.RealmMBean", "weblogic.management.configuration.RealmMBeanImplBeanInfo");
      interfaceMap.put("weblogic.management.configuration.RemoteSAFContextMBean", "weblogic.management.configuration.RemoteSAFContextMBeanImplBeanInfo");
      interfaceMap.put("weblogic.management.configuration.ResponseTimeRequestClassMBean", "weblogic.management.configuration.ResponseTimeRequestClassMBeanImplBeanInfo");
      interfaceMap.put("weblogic.management.configuration.RestfulManagementServicesMBean", "weblogic.management.configuration.RestfulManagementServicesMBeanImplBeanInfo");
      interfaceMap.put("weblogic.management.configuration.SAFAgentMBean", "weblogic.management.configuration.SAFAgentMBeanImplBeanInfo");
      interfaceMap.put("weblogic.management.configuration.SCAContainerMBean", "weblogic.management.configuration.SCAContainerMBeanImplBeanInfo");
      interfaceMap.put("weblogic.management.configuration.SNMPAgentDeploymentMBean", "weblogic.management.configuration.SNMPAgentDeploymentMBeanImplBeanInfo");
      interfaceMap.put("weblogic.management.configuration.SNMPAgentMBean", "weblogic.management.configuration.SNMPAgentMBeanImplBeanInfo");
      interfaceMap.put("weblogic.management.configuration.SNMPAttributeChangeMBean", "weblogic.management.configuration.SNMPAttributeChangeMBeanImplBeanInfo");
      interfaceMap.put("weblogic.management.configuration.SNMPCounterMonitorMBean", "weblogic.management.configuration.SNMPCounterMonitorMBeanImplBeanInfo");
      interfaceMap.put("weblogic.management.configuration.SNMPGaugeMonitorMBean", "weblogic.management.configuration.SNMPGaugeMonitorMBeanImplBeanInfo");
      interfaceMap.put("weblogic.management.configuration.SNMPJMXMonitorMBean", "weblogic.management.configuration.SNMPJMXMonitorMBeanImplBeanInfo");
      interfaceMap.put("weblogic.management.configuration.SNMPLogFilterMBean", "weblogic.management.configuration.SNMPLogFilterMBeanImplBeanInfo");
      interfaceMap.put("weblogic.management.configuration.SNMPProxyMBean", "weblogic.management.configuration.SNMPProxyMBeanImplBeanInfo");
      interfaceMap.put("weblogic.management.configuration.SNMPStringMonitorMBean", "weblogic.management.configuration.SNMPStringMonitorMBeanImplBeanInfo");
      interfaceMap.put("weblogic.management.configuration.SNMPTrapDestinationMBean", "weblogic.management.configuration.SNMPTrapDestinationMBeanImplBeanInfo");
      interfaceMap.put("weblogic.management.configuration.SNMPTrapSourceMBean", "weblogic.management.configuration.SNMPTrapSourceMBeanImplBeanInfo");
      interfaceMap.put("weblogic.management.configuration.SSLMBean", "weblogic.management.configuration.SSLMBeanImplBeanInfo");
      interfaceMap.put("weblogic.management.configuration.SecurityConfigurationMBean", "weblogic.management.configuration.SecurityConfigurationMBeanImplBeanInfo");
      interfaceMap.put("weblogic.management.configuration.SecurityMBean", "weblogic.management.configuration.SecurityMBeanImplBeanInfo");
      interfaceMap.put("weblogic.management.configuration.SelfTuningMBean", "weblogic.management.configuration.SelfTuningMBeanImplBeanInfo");
      interfaceMap.put("weblogic.management.configuration.ServerDebugMBean", "weblogic.management.configuration.ServerDebugMBeanImplBeanInfo");
      interfaceMap.put("weblogic.management.configuration.ServerFailureTriggerMBean", "weblogic.management.configuration.ServerFailureTriggerMBeanImplBeanInfo");
      interfaceMap.put("weblogic.management.configuration.ServerMBean", "weblogic.management.configuration.ServerMBeanImplBeanInfo");
      interfaceMap.put("weblogic.management.configuration.ServerStartMBean", "weblogic.management.configuration.ServerStartMBeanImplBeanInfo");
      interfaceMap.put("weblogic.management.configuration.ShutdownClassMBean", "weblogic.management.configuration.ShutdownClassMBeanImplBeanInfo");
      interfaceMap.put("weblogic.management.configuration.SingleSignOnServicesMBean", "weblogic.management.configuration.SingleSignOnServicesMBeanImplBeanInfo");
      interfaceMap.put("weblogic.management.configuration.SingletonServiceAppScopedMBean", "weblogic.management.configuration.SingletonServiceAppScopedMBeanImplBeanInfo");
      interfaceMap.put("weblogic.management.configuration.SingletonServiceBaseMBean", "weblogic.management.configuration.SingletonServiceBaseMBeanImplBeanInfo");
      interfaceMap.put("weblogic.management.configuration.SingletonServiceMBean", "weblogic.management.configuration.SingletonServiceMBeanImplBeanInfo");
      interfaceMap.put("weblogic.management.configuration.StartupClassMBean", "weblogic.management.configuration.StartupClassMBeanImplBeanInfo");
      interfaceMap.put("weblogic.management.configuration.StuckThreadActionMBean", "weblogic.management.configuration.StuckThreadActionMBeanImplBeanInfo");
      interfaceMap.put("weblogic.management.configuration.SubDeploymentMBean", "weblogic.management.configuration.SubDeploymentMBeanImplBeanInfo");
      interfaceMap.put("weblogic.management.configuration.SystemResourceMBean", "weblogic.management.configuration.SystemResourceMBeanImplBeanInfo");
      interfaceMap.put("weblogic.management.configuration.TargetInfoMBean", "weblogic.management.configuration.TargetInfoMBeanImplBeanInfo");
      interfaceMap.put("weblogic.management.configuration.TargetMBean", "weblogic.management.configuration.TargetMBeanImplBeanInfo");
      interfaceMap.put("weblogic.management.configuration.TransactionLogJDBCStoreMBean", "weblogic.management.configuration.TransactionLogJDBCStoreMBeanImplBeanInfo");
      interfaceMap.put("weblogic.management.configuration.TransactionLogStoreMBean", "weblogic.management.configuration.TransactionLogStoreMBeanImplBeanInfo");
      interfaceMap.put("weblogic.management.configuration.UnixMachineMBean", "weblogic.management.configuration.UnixMachineMBeanImplBeanInfo");
      interfaceMap.put("weblogic.management.configuration.UnixRealmMBean", "weblogic.management.configuration.UnixRealmMBeanImplBeanInfo");
      interfaceMap.put("weblogic.management.configuration.VirtualDestinationMBean", "weblogic.management.configuration.VirtualDestinationMBeanImplBeanInfo");
      interfaceMap.put("weblogic.management.configuration.VirtualHostMBean", "weblogic.management.configuration.VirtualHostMBeanImplBeanInfo");
      interfaceMap.put("weblogic.management.configuration.WLDFDataRetirementByAgeMBean", "weblogic.management.configuration.WLDFDataRetirementByAgeMBeanImplBeanInfo");
      interfaceMap.put("weblogic.management.configuration.WLDFDataRetirementMBean", "weblogic.management.configuration.WLDFDataRetirementMBeanImplBeanInfo");
      interfaceMap.put("weblogic.management.configuration.WLDFServerDiagnosticMBean", "weblogic.management.configuration.WLDFServerDiagnosticMBeanImplBeanInfo");
      interfaceMap.put("weblogic.management.configuration.WLDFSystemResourceMBean", "weblogic.management.configuration.WLDFSystemResourceMBeanImplBeanInfo");
      interfaceMap.put("weblogic.management.configuration.WLECConnectionPoolMBean", "weblogic.management.configuration.WLECConnectionPoolMBeanImplBeanInfo");
      interfaceMap.put("weblogic.management.configuration.WSReliableDeliveryPolicyMBean", "weblogic.management.configuration.WSReliableDeliveryPolicyMBeanImplBeanInfo");
      interfaceMap.put("weblogic.management.configuration.WTCExportMBean", "weblogic.management.configuration.WTCExportMBeanImplBeanInfo");
      interfaceMap.put("weblogic.management.configuration.WTCImportMBean", "weblogic.management.configuration.WTCImportMBeanImplBeanInfo");
      interfaceMap.put("weblogic.management.configuration.WTCLocalTuxDomMBean", "weblogic.management.configuration.WTCLocalTuxDomMBeanImplBeanInfo");
      interfaceMap.put("weblogic.management.configuration.WTCPasswordMBean", "weblogic.management.configuration.WTCPasswordMBeanImplBeanInfo");
      interfaceMap.put("weblogic.management.configuration.WTCRemoteTuxDomMBean", "weblogic.management.configuration.WTCRemoteTuxDomMBeanImplBeanInfo");
      interfaceMap.put("weblogic.management.configuration.WTCResourcesMBean", "weblogic.management.configuration.WTCResourcesMBeanImplBeanInfo");
      interfaceMap.put("weblogic.management.configuration.WTCServerMBean", "weblogic.management.configuration.WTCServerMBeanImplBeanInfo");
      interfaceMap.put("weblogic.management.configuration.WTCtBridgeGlobalMBean", "weblogic.management.configuration.WTCtBridgeGlobalMBeanImplBeanInfo");
      interfaceMap.put("weblogic.management.configuration.WTCtBridgeRedirectMBean", "weblogic.management.configuration.WTCtBridgeRedirectMBeanImplBeanInfo");
      interfaceMap.put("weblogic.management.configuration.WebAppComponentMBean", "weblogic.management.configuration.WebAppComponentMBeanImplBeanInfo");
      interfaceMap.put("weblogic.management.configuration.WebAppContainerMBean", "weblogic.management.configuration.WebAppContainerMBeanImplBeanInfo");
      interfaceMap.put("weblogic.management.configuration.WebDeploymentMBean", "weblogic.management.configuration.WebDeploymentMBeanImplBeanInfo");
      interfaceMap.put("weblogic.management.configuration.WebServerLogMBean", "weblogic.management.configuration.WebServerLogMBeanImplBeanInfo");
      interfaceMap.put("weblogic.management.configuration.WebServerMBean", "weblogic.management.configuration.WebServerMBeanImplBeanInfo");
      interfaceMap.put("weblogic.management.configuration.WebServiceBufferingMBean", "weblogic.management.configuration.WebServiceBufferingMBeanImplBeanInfo");
      interfaceMap.put("weblogic.management.configuration.WebServiceBufferingQueueMBean", "weblogic.management.configuration.WebServiceBufferingQueueMBeanImplBeanInfo");
      interfaceMap.put("weblogic.management.configuration.WebServiceComponentMBean", "weblogic.management.configuration.WebServiceComponentMBeanImplBeanInfo");
      interfaceMap.put("weblogic.management.configuration.WebServiceLogicalStoreMBean", "weblogic.management.configuration.WebServiceLogicalStoreMBeanImplBeanInfo");
      interfaceMap.put("weblogic.management.configuration.WebServiceMBean", "weblogic.management.configuration.WebServiceMBeanImplBeanInfo");
      interfaceMap.put("weblogic.management.configuration.WebServicePersistenceMBean", "weblogic.management.configuration.WebServicePersistenceMBeanImplBeanInfo");
      interfaceMap.put("weblogic.management.configuration.WebServicePhysicalStoreMBean", "weblogic.management.configuration.WebServicePhysicalStoreMBeanImplBeanInfo");
      interfaceMap.put("weblogic.management.configuration.WebServiceReliabilityMBean", "weblogic.management.configuration.WebServiceReliabilityMBeanImplBeanInfo");
      interfaceMap.put("weblogic.management.configuration.WebServiceRequestBufferingQueueMBean", "weblogic.management.configuration.WebServiceRequestBufferingQueueMBeanImplBeanInfo");
      interfaceMap.put("weblogic.management.configuration.WebServiceResponseBufferingQueueMBean", "weblogic.management.configuration.WebServiceResponseBufferingQueueMBeanImplBeanInfo");
      interfaceMap.put("weblogic.management.configuration.WebserviceCredentialProviderMBean", "weblogic.management.configuration.WebserviceCredentialProviderMBeanImplBeanInfo");
      interfaceMap.put("weblogic.management.configuration.WebserviceSecurityConfigurationMBean", "weblogic.management.configuration.WebserviceSecurityConfigurationMBeanImplBeanInfo");
      interfaceMap.put("weblogic.management.configuration.WebserviceSecurityMBean", "weblogic.management.configuration.WebserviceSecurityMBeanImplBeanInfo");
      interfaceMap.put("weblogic.management.configuration.WebserviceSecurityTokenMBean", "weblogic.management.configuration.WebserviceSecurityTokenMBeanImplBeanInfo");
      interfaceMap.put("weblogic.management.configuration.WebserviceTimestampMBean", "weblogic.management.configuration.WebserviceTimestampMBeanImplBeanInfo");
      interfaceMap.put("weblogic.management.configuration.WebserviceTokenHandlerMBean", "weblogic.management.configuration.WebserviceTokenHandlerMBeanImplBeanInfo");
      interfaceMap.put("weblogic.management.configuration.WorkManagerMBean", "weblogic.management.configuration.WorkManagerMBeanImplBeanInfo");
      interfaceMap.put("weblogic.management.configuration.WorkManagerShutdownTriggerMBean", "weblogic.management.configuration.WorkManagerShutdownTriggerMBeanImplBeanInfo");
      interfaceMap.put("weblogic.management.configuration.XMLEntityCacheMBean", "weblogic.management.configuration.XMLEntityCacheMBeanImplBeanInfo");
      interfaceMap.put("weblogic.management.configuration.XMLEntitySpecRegistryEntryMBean", "weblogic.management.configuration.XMLEntitySpecRegistryEntryMBeanImplBeanInfo");
      interfaceMap.put("weblogic.management.configuration.XMLParserSelectRegistryEntryMBean", "weblogic.management.configuration.XMLParserSelectRegistryEntryMBeanImplBeanInfo");
      interfaceMap.put("weblogic.management.configuration.XMLRegistryEntryMBean", "weblogic.management.configuration.XMLRegistryEntryMBeanImplBeanInfo");
      interfaceMap.put("weblogic.management.configuration.XMLRegistryMBean", "weblogic.management.configuration.XMLRegistryMBeanImplBeanInfo");
      roleInfoList = new ArrayList(72);
      roleInfoList.add("weblogic.management.configuration.AppDeploymentMBean");
      roleInfoList.add("weblogic.management.configuration.ApplicationMBean");
      roleInfoList.add("weblogic.management.configuration.BasicDeploymentMBean");
      roleInfoList.add("weblogic.management.configuration.ClusterMBean");
      roleInfoList.add("weblogic.management.configuration.CoherenceClusterSystemResourceMBean");
      roleInfoList.add("weblogic.management.configuration.CoherenceServerMBean");
      roleInfoList.add("weblogic.management.configuration.ComponentMBean");
      roleInfoList.add("weblogic.management.configuration.ConnectorComponentMBean");
      roleInfoList.add("weblogic.management.configuration.CustomResourceMBean");
      roleInfoList.add("weblogic.management.configuration.DataSourceMBean");
      roleInfoList.add("weblogic.management.configuration.DomainLibraryMBean");
      roleInfoList.add("weblogic.management.configuration.DomainMBean");
      roleInfoList.add("weblogic.management.configuration.EJBComponentMBean");
      roleInfoList.add("weblogic.management.configuration.ForeignJMSServerMBean");
      roleInfoList.add("weblogic.management.configuration.JDBCConnectionPoolMBean");
      roleInfoList.add("weblogic.management.configuration.JDBCDataSourceFactoryMBean");
      roleInfoList.add("weblogic.management.configuration.JDBCDataSourceMBean");
      roleInfoList.add("weblogic.management.configuration.JDBCMultiPoolMBean");
      roleInfoList.add("weblogic.management.configuration.JDBCPoolComponentMBean");
      roleInfoList.add("weblogic.management.configuration.JDBCStoreMBean");
      roleInfoList.add("weblogic.management.configuration.JDBCSystemResourceMBean");
      roleInfoList.add("weblogic.management.configuration.JDBCTxDataSourceMBean");
      roleInfoList.add("weblogic.management.configuration.JMSBridgeDestinationMBean");
      roleInfoList.add("weblogic.management.configuration.JMSConnectionConsumerMBean");
      roleInfoList.add("weblogic.management.configuration.JMSConnectionFactoryMBean");
      roleInfoList.add("weblogic.management.configuration.JMSDestCommonMBean");
      roleInfoList.add("weblogic.management.configuration.JMSDestinationKeyMBean");
      roleInfoList.add("weblogic.management.configuration.JMSDestinationMBean");
      roleInfoList.add("weblogic.management.configuration.JMSDistributedDestinationMBean");
      roleInfoList.add("weblogic.management.configuration.JMSDistributedDestinationMemberMBean");
      roleInfoList.add("weblogic.management.configuration.JMSDistributedQueueMBean");
      roleInfoList.add("weblogic.management.configuration.JMSDistributedQueueMemberMBean");
      roleInfoList.add("weblogic.management.configuration.JMSDistributedTopicMBean");
      roleInfoList.add("weblogic.management.configuration.JMSDistributedTopicMemberMBean");
      roleInfoList.add("weblogic.management.configuration.JMSFileStoreMBean");
      roleInfoList.add("weblogic.management.configuration.JMSInteropModuleMBean");
      roleInfoList.add("weblogic.management.configuration.JMSJDBCStoreMBean");
      roleInfoList.add("weblogic.management.configuration.JMSQueueMBean");
      roleInfoList.add("weblogic.management.configuration.JMSServerMBean");
      roleInfoList.add("weblogic.management.configuration.JMSSessionPoolMBean");
      roleInfoList.add("weblogic.management.configuration.JMSStoreMBean");
      roleInfoList.add("weblogic.management.configuration.JMSSystemResourceMBean");
      roleInfoList.add("weblogic.management.configuration.JMSTemplateMBean");
      roleInfoList.add("weblogic.management.configuration.JMSTopicMBean");
      roleInfoList.add("weblogic.management.configuration.JoltConnectionPoolMBean");
      roleInfoList.add("weblogic.management.configuration.LibraryMBean");
      roleInfoList.add("weblogic.management.configuration.SecurityConfigurationMBean");
      roleInfoList.add("weblogic.management.configuration.ServerMBean");
      roleInfoList.add("weblogic.management.configuration.ShutdownClassMBean");
      roleInfoList.add("weblogic.management.configuration.SingletonServiceAppScopedMBean");
      roleInfoList.add("weblogic.management.configuration.StartupClassMBean");
      roleInfoList.add("weblogic.management.configuration.SubDeploymentMBean");
      roleInfoList.add("weblogic.management.configuration.SystemResourceMBean");
      roleInfoList.add("weblogic.management.configuration.TargetInfoMBean");
      roleInfoList.add("weblogic.management.configuration.TransactionLogJDBCStoreMBean");
      roleInfoList.add("weblogic.management.configuration.VirtualHostMBean");
      roleInfoList.add("weblogic.management.configuration.WLDFServerDiagnosticMBean");
      roleInfoList.add("weblogic.management.configuration.WLDFSystemResourceMBean");
      roleInfoList.add("weblogic.management.configuration.WSReliableDeliveryPolicyMBean");
      roleInfoList.add("weblogic.management.configuration.WTCExportMBean");
      roleInfoList.add("weblogic.management.configuration.WTCImportMBean");
      roleInfoList.add("weblogic.management.configuration.WTCLocalTuxDomMBean");
      roleInfoList.add("weblogic.management.configuration.WTCPasswordMBean");
      roleInfoList.add("weblogic.management.configuration.WTCRemoteTuxDomMBean");
      roleInfoList.add("weblogic.management.configuration.WTCResourcesMBean");
      roleInfoList.add("weblogic.management.configuration.WTCServerMBean");
      roleInfoList.add("weblogic.management.configuration.WTCtBridgeGlobalMBean");
      roleInfoList.add("weblogic.management.configuration.WTCtBridgeRedirectMBean");
      roleInfoList.add("weblogic.management.configuration.WebAppComponentMBean");
      roleInfoList.add("weblogic.management.configuration.WebDeploymentMBean");
      roleInfoList.add("weblogic.management.configuration.WebServerMBean");
      roleInfoList.add("weblogic.management.configuration.WebServiceComponentMBean");
      SINGLETON = new BeanInfoFactory();
   }
}
