package weblogic.deployment.descriptors;

public interface DDValidationErrorCodes {
   String DEPLOYMENT_DESCRIPTOR_BUNDLE = "weblogic.deployment.descriptors.DDValidationBundle";
   String ENV_VALUE_NOT_OF_TYPE = "ENV_VALUE_NOT_OF_TYPE";
   String INVALID_EJB_REF_TYPE = "INVALID_EJB_REF_TYPE";
   String INVALID_ENV_TYPE = "INVALID_ENV_TYPE";
   String INVALID_RES_AUTH = "INVALID_RES_AUTH";
   String INVALID_RES_JNDI_NAME = "INVALID_RES_JNDI_NAME";
   String INVALID_RES_TYPE = "INVALID_RES_TYPE";
   String NO_EJB_REF_HOME_SET = "NO_EJB_REF_HOME_SET";
   String NO_EJB_REF_EJB_NAME_SET = "NO_EJB_REF_EJB_NAME_SET";
   String NO_EJB_REF_JNDI_NAME_SET = "NO_EJB_REF_JNDI_NAME_SET";
   String NO_EJB_REF_NAME_SET = "NO_EJB_REF_NAME_SET";
   String NO_EJB_REF_REMOTE_SET = "NO_EJB_REF_REMOTE_SET";
   String NO_EJB_REF_TYPE_SET = "NO_EJB_REF_TYPE_SET";
   String NO_ENV_ENTRY_NAME_SET = "NO_ENV_ENTRY_NAME_SET";
   String NO_ENV_ENTRY_VALUE_SET = "NO_ENV_ENTRY_VALUE_SET";
   String NO_RES_AUTH_SET = "NO_RES_AUTH_SET";
   String NO_RES_JNDI_NAME = "NO_RES_JNDI_NAME";
   String NO_RES_REF_NAME_SET = "NO_RES_REF_NAME_SET";
   String NO_RES_REF_TYPE_SET = "NO_RES_REF_TYPE_SET";
   String NO_ROLE_NAME_SET = "NO_ROLE_NAME_SET";
   String NO_SEC_ROLE_REF_NAME = "NO_SEC_ROLE_REF_NAME";
   String NO_SEC_ROLE_REF_ROLE = "NO_SEC_ROLE_REF_ROLE";
}
