package weblogic.ejb.container.dd;

import java.util.HashMap;
import java.util.HashSet;
import java.util.Map;
import java.util.Set;

public final class DDConstants extends weblogic.ejb.spi.DDConstants {
   public static final String DEPLOYMENT_DEBUG_PROP = "weblogic.ejb.deployment.debug";
   public static final String DEPLOYMENT_VERBOSE_PROP = "weblogic.ejb.deployment.verbose";
   public static final String EJB_JAR_XML_FILENAME = "ejb-jar.xml";
   public static final String WL_EJB_JAR_XML_FILENAME = "weblogic-ejb-jar.xml";
   public static final String[] validEjbJarPublicIds = new String[]{"-//Sun Microsystems, Inc.//DTD Enterprise JavaBeans 1.1//EN", "-//Sun Microsystems, Inc.//DTD Enterprise JavaBeans 2.0//EN"};
   public static final String[] validWeblogicEjbJarPublicIds = new String[]{"-//BEA Systems, Inc.//DTD WebLogic 5.1.0 EJB//EN", "-//BEA Systems, Inc.//DTD WebLogic 6.0.0 EJB//EN", "-//BEA Systems, Inc.//DTD WebLogic 7.0.0 EJB//EN", "-//BEA Systems, Inc.//DTD WebLogic 8.1.0 EJB//EN"};
   public static final String DEPLOYMENT_DESCRIPTOR_BUNDLE = "weblogic.ejb.deployment.dd.DescriptorBundle";
   public static final String DESCRIPTOR_LOADER_BUNDLE = "weblogic.ejb.deployment.dd.LoaderBundle";
   public static final short TX_NOT_SET = -1;
   public static final short TX_NOT_SUPPORTED = 0;
   public static final short TX_REQUIRED = 1;
   public static final short TX_SUPPORTS = 2;
   public static final short TX_REQUIRES_NEW = 3;
   public static final short TX_MANDATORY = 4;
   public static final short TX_NEVER = 5;
   public static final Map VALID_TX_ATTRIBUTES = new HashMap();
   public static final String[] TX_ATTRIBUTE_STRINGS = new String[]{"NotSupported", "Required", "Supports", "RequiresNew", "Mandatory", "Never"};
   public static final String ROUND_ROBIN = "round-robin";
   public static final String RANDOM = "random";
   public static final String WEIGHT_BASED = "weight-based";
   public static final String WEBSERVICE = "ServiceEndpoint";
   public static final String MESSAGINGTYPE = "MessagingType";
   public static final short CMP_VERSION_1X = 1;
   public static final short CMP_VERSION_2X = 2;
   public static final String DROPANDCREATE = "DropAndCreate";
   public static final String DROPANDCREATEALWAYS = "DropAndCreateAlways";
   public static final String ALTERORCREATE = "AlterOrCreate";
   public static final String CREATEONLY = "CreateOnly";
   public static final String DISABLED = "Disabled";
   public static final String[] CREATE_DEFAULT_DBMS_TABLES_VALUES = new String[]{"DropAndCreate", "DropAndCreateAlways", "AlterOrCreate", "CreateOnly", "Disabled"};
   public static final String GROUPBY = "GROUPBY";
   public static final String ORDERBY = "ORDERBY";
   public static final String SELECT = "SELECT";
   public static final String FROM = "FROM";
   public static final String WHERE = "WHERE";
   public static final Set reservedWords = new HashSet();
   public static final String TEMPCOLUMNNAME = "WLS_TEMP";
   public static final int SELECT_FOR_UPDATE_DISABLED = 0;
   public static final int SELECT_FOR_UPDATE = 1;
   public static final int SELECT_FOR_UPDATE_NO_WAIT = 2;
   public static final int UPDATE_LOCK_NONE = 4;
   public static final int UPDATE_LOCK_AS_GENERATED = 5;
   public static final int UPDATE_LOCK_TX_LEVEL = 6;
   public static final int UPDATE_LOCK_TX_LEVEL_NO_WAIT = 7;
   public static final int DB_UNKNOWN = 0;
   public static final int DB_ORACLE = 1;
   public static final int DB_SQLSERVER = 2;
   public static final int DB_INFORMIX = 3;
   public static final int DB_DB2 = 4;
   public static final int DB_SYBASE = 5;
   public static final int DB_POINTBASE = 6;
   public static final int DB_SQLSERVER_2000 = 7;
   public static final int DB_MYSQL = 8;
   public static final int DB_DERBY = 9;
   public static final Map DBTYPE_MAP;
   public static final String[] DBTYPE_NAMES;
   public static final int INSERT = 0;
   public static final int UPDATE = 1;
   public static final int DELETE = 2;
   public static final String BEA_010054 = "BEA-010054";
   public static final String BEA_010202 = "BEA-010202";
   public static final String BEA_010001 = "BEA-010001";
   public static final String BEA_010200 = "BEA-010200";
   public static final String BEA_012034 = "BEA-012034";
   public static final String messageSelector = "MESSAGESELECTOR";
   public static final String acknowledgeMode = "ACKNOWLEDGEMODE";
   public static final String destinationType = "DESTINATIONTYPE";
   public static final String subscriptionDurability = "SUBSCRIPTIONDURABILITY";
   public static final String connectionFactoryJNDIName = "CONNECTIONFACTORYJNDINAME";
   public static final String destinationJNDIName = "DESTINATIONJNDINAME";
   public static final String resourceAdapterJNDIName = "RESOURCEADAPTERJNDINAME";
   public static final String destinationResourceLink = "DESTINATIONRESOURCELINK";
   public static final String connectionFactoryResourceLink = "CONNECTIONFACTORYRESOURCELINK";
   public static final String distributedDestinationConnection = "DISTRIBUTEDDESTINATIONCONNECTION";
   public static final String jmsClientId = "JMSCLIENTID";
   public static final String durableSubscriptionDeletion = "DURABLESUBSCRIPTIONDELETION";
   public static final String jmsPollingIntervalSeconds = "JMSPOLLINGINTERVALSECONDS";
   public static final String initialContextFactory = "INITIALCONTEXTFACTORY";
   public static final String providerUrl = "PROVIDERURL";
   public static final String maxMessagesInTransaction = "MAXMESSAGESINTRANSACTION";
   public static final String initSuspendSeconds = "INITSUSPENDSECONDS";
   public static final String maxSuspendSeconds = "MAXSUSPENDSECONDS";
   public static final String use81StylePolling = "USE81STYLEPOLLING";
   public static final String minimizeAQSessions = "MINIMIZEAQSESSIONS";
   public static final String topicMessagesDistributionMode = "TOPICMESSAGESDISTRIBUTIONMODE";
   public static final String inactive = "INACTIVE";
   public static final Set<String> updateElementSet;
   public static final int REPLICATEDTOPIC = 1;
   public static final int PARTITIONEDTOPIC = 2;
   public static final int EVERYMEMBER = 1;
   public static final int LOCALONLY = 0;
   public static final String[] DISTRIBUTEDDESTINATIONCONNECTIONS;
   public static final int COMPATIBILITYY = 0;
   public static final int ONE_COPY_PER_SERVER = 1;
   public static final int ONE_COPY_PER_APPLICATION = 2;
   public static final String[] TOPICMESSAGEDISTRIBUTIONMODES;
   public static final String[] MDBStatus;
   public static final int INITIALIZING = 0;
   public static final int ACTIVE = 1;
   public static final int RUNNING = 2;
   public static final int SUSPENDED = 3;
   public static final int ERROR = 4;
   public static final int INACTIVE = 5;

   public static String getDBNameForType(int var0) {
      return var0 < DBTYPE_NAMES.length && var0 >= 0 ? DBTYPE_NAMES[var0] : "UNKNOWN";
   }

   static {
      VALID_TX_ATTRIBUTES.put("NotSupported", new Short((short)0));
      VALID_TX_ATTRIBUTES.put("Required", new Short((short)1));
      VALID_TX_ATTRIBUTES.put("Supports", new Short((short)2));
      VALID_TX_ATTRIBUTES.put("RequiresNew", new Short((short)3));
      VALID_TX_ATTRIBUTES.put("Mandatory", new Short((short)4));
      VALID_TX_ATTRIBUTES.put("Never", new Short((short)5));
      reservedWords.add("GROUPBY");
      reservedWords.add("ORDERBY");
      reservedWords.add("SELECT");
      reservedWords.add("FROM");
      reservedWords.add("WHERE");
      reservedWords.add("WLS_TEMP");
      DBTYPE_MAP = new HashMap();
      DBTYPE_MAP.put("ORACLE", new Integer(1));
      DBTYPE_MAP.put("SQL_SERVER", new Integer(2));
      DBTYPE_MAP.put("SQLSERVER", new Integer(2));
      DBTYPE_MAP.put("INFORMIX", new Integer(3));
      DBTYPE_MAP.put("DB2", new Integer(4));
      DBTYPE_MAP.put("SYBASE", new Integer(5));
      DBTYPE_MAP.put("POINTBASE", new Integer(6));
      DBTYPE_MAP.put("SQLSERVER2000", new Integer(7));
      DBTYPE_MAP.put("MYSQL", new Integer(8));
      DBTYPE_MAP.put("DERBY", new Integer(9));
      DBTYPE_NAMES = new String[]{"UNKNOWN", "ORACLE", "SQLSERVER", "INFORMIX", "DB2", "SYBASE", "POINTBASE", "SQLSERVER2000", "MYSQL"};
      updateElementSet = new HashSet<String>() {
         {
            this.add("MESSAGESELECTOR");
            this.add("INACTIVE");
            this.add("TOPICMESSAGESDISTRIBUTIONMODE");
         }
      };
      DISTRIBUTEDDESTINATIONCONNECTIONS = new String[]{"LocalOnly", "EveryMember"};
      TOPICMESSAGEDISTRIBUTIONMODES = new String[]{"Compatibility", "One-Copy-Per-Server", "One-Copy-Per-Application"};
      MDBStatus = new String[]{"INITIALIZING", "ACTIVE", "RUNNING", "SUSPENDED", "ERROR", "INACTIVE"};
   }
}
